### ISSUE TITLE
I want to get more information about it

### ISSUE THREAD

**Issue by FPGA-KING** [ultraembedded/usb_sniffer#3]
Hello. I can't find How to wiring FPGA and SMSC USB3343 ULPI PHY Evalutation board.

and WIKI also has no any helpful inforamtion.

Is it possible buy OpenVizsla kickstarter Board ? 

Thanks.

**Comment by ultraembedded** [comment]
Hi,

If you have that combinations of boards (minispartan6, waveshare ulpi board), the connections are specified in the UCF file;

NET  "USB_ULPI_DATA<0>"		LOC = "M14" ;
NET  "USB_ULPI_DATA<1>"		LOC = "L13" ;
NET  "USB_ULPI_DATA<2>"		LOC = "L14" ;
NET  "USB_ULPI_DATA<3>"		LOC = "K14" ;
NET  "USB_ULPI_DATA<4>"		LOC = "J12" ;
NET  "USB_ULPI_DATA<5>"		LOC = "M13" ;
NET  "USB_ULPI_DATA<6>"		LOC = "M12" ;
NET  "USB_ULPI_DATA<7>"		LOC = "P12" ;
NET  "USB_ULPI_STP"			LOC = "M11" ;
NET  "USB_ULPI_NXT"			LOC = "N12" ;
NET  "USB_ULPI_DIR"			LOC = "N14" ;
NET  "USB_CLK60"			LOC = "J13"

These map to ‘digital header C’ on the minispartan6, which is defined as;

NET "PORTC0"  LOC="J13" | IOSTANDARD=LVTTL;
NET "PORTC1"  LOC="J12" | IOSTANDARD=LVTTL;
NET "PORTC2"  LOC="K14" | IOSTANDARD=LVTTL;
NET "PORTC3"  LOC="L14" | IOSTANDARD=LVTTL;
NET "PORTC4"  LOC="L13" | IOSTANDARD=LVTTL;
NET "PORTC5"  LOC="M14" | IOSTANDARD=LVTTL;
NET "PORTC6"  LOC="M13" | IOSTANDARD=LVTTL;
NET "PORTC7"  LOC="N14" | IOSTANDARD=LVTTL;
NET "PORTC8"  LOC="M12" | IOSTANDARD=LVTTL;
NET "PORTC9"  LOC="N12" | IOSTANDARD=LVTTL;
NET "PORTC10" LOC="P12" | IOSTANDARD=LVTTL;
NET "PORTC11" LOC="M11" | IOSTANDARD=LVTTL;

You can change this mapping but be aware that only some pins are clock capable.
